import { ReactNode } from "react";
import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";

const inter = Inter({ subsets: ["latin"] });

type AppProps = {
	children: ReactNode;
};

export const App = ({ children }: AppProps) => {
	return (
		<>
			<Head>
				<title>Resume</title>
				<meta name="description" content="Generated by create next app" />
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				{/* <link rel="icon" href="/favicon.ico" /> */}
				<link
					rel="stylesheet"
					href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
				/>
			</Head>
			<main>{children}</main>
		</>
	);
};
